baseURL = "https://www.mattlayman.com/"
languageCode = "en-us"
title = "Matt Layman"
theme = "tailwind-site"
canonifyURLs = true
enableRobotsTXT = true
paginate = 18
pygmentsCodeFences = true

[markup.goldmark.renderer]
unsafe= true

[frontmatter]
    date = [":filename", ":default"]

[params]
    title = "Matt Layman"
    subtitle = "A software creator / Django consultant"
    copyright = "© 2008–2020 Matt Layman"
    cover = "img/paint.jpg"
    description = "Matt Layman is a software engineer from Frederick, MD. He is an open source software maintainer and advocate for the Python programming language."

    twitterName = "mblayman"
    githubName = "mblayman"
    linkedinName = "mattlayman"

    authorAvatar = "img/me.jpg"

[permalinks]
    blog = "/blog/:year/:slug/"
